version: "2"
run:
  tests: true
linters:
  enable:
    - contextcheck
    - copyloopvar
    - depguard
    - dupword
    - errorlint
    - gosec
    - loggercheck
    - mirror
    - misspell
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - testifylint
    - thelper
    - usestdlibvars
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
            - pkg: golang.org/x/net/context
              desc: Should be replaced by standard lib context package
    loggercheck:
      require-string-key: true
      no-printf-like: true
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: true
    revive:
      enable-all-rules: true
      rules:
        - name: cognitive-complexity
          arguments:
            - 7
          severity: warning
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T'
        - name: cyclomatic
          arguments:
            - 5
        - name: exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
        - name: unhandled-error
          arguments:
            - fmt.Print.*
            - fmt.Fprint.*
            - bytes.Buffer.Write
            - bytes.Buffer.WriteByte
            - bytes.Buffer.WriteString
            - strings.Builder.WriteString
            - strings.Builder.WriteRune
        - name: flag-parameter
          disabled: true
        - name: imports-blocklist
          disabled: true
        - name: nested-structs
          disabled: true
        - name: add-constant
          disabled: true
        - name: modifies-value-receiver
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: argument-limit
          disabled: true
        - name: banned-characters
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: function-length
          disabled: true
        - name: file-header
          disabled: true
        - name: empty-lines
          disabled: true
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
